### ISSUE TITLE
Please document behaviour of -k 0 option

### ISSUE THREAD

**Issue by 15knots** [ninja-build/ninja#1006]
- same as `-k 1`?
- keep going until infinite number of  jobs fail?

**Comment by nico** [comment]
`-k 0` is "keep going". Yes, we should fix this.

**Comment by tfarina** [comment]
@martine looks like this is a dup of https://github.com/ninja-build/ninja/issues/1056, where there is an attempt to document it.

**Comment by 15knots** [comment]
Am Freitag, 4. Dezember 2015, 07:20:34 schrieb Thiago Farina:
> @martine looks like this is a dup of
> https://github.com/ninja-build/ninja/issues/1056, where there is an attempt
> to document it.

Definitely a dup.

Martin

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by luoxing91** [comment]
-k is not working as document say.

$ninja -k 5 ;
[1/7] Building CXX object confget/CMakeFiles/cmdb.dir/cmdb.cc.o
FAILED: confget/CMakeFiles/cmdb.dir/cmdb.cc.o 
/Library/Developer/CommandLineTools/usr/bin/c++   -I/usr/local/include -I/home/luoxing/include -I/Users/didi/include -Wall -std=c++11 -Wall -std=c++1y -MD -MT confget/CMakeFiles/cmdb.dir/cmdb.cc.o -MF confget/CMakeFiles/cmdb.dir/cmdb.cc.o.d -o confget/CMakeFiles/cmdb.dir/cmdb.cc.o -c ../confget/cmdb.cc
../confget/cmdb.cc:1:10: fatal error: 'boost/beast/core.hpp' file not found
#include <boost/beast/core.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[2/7] Building CXX object confget/CMakeFiles/etcd.dir/etcd.cc.o
FAILED: confget/CMakeFiles/etcd.dir/etcd.cc.o 
/Library/Developer/CommandLineTools/usr/bin/c++   -I/usr/local/include -I/home/luoxing/include -I/Users/didi/include -Wall -std=c++11 -Wall -std=c++1y -MD -MT confget/CMakeFiles/etcd.dir/etcd.cc.o -MF confget/CMakeFiles/etcd.dir/etcd.cc.o.d -o confget/CMakeFiles/etcd.dir/etcd.cc.o -c ../confget/etcd.cc
../confget/etcd.cc:1:10: fatal error: 'boost/beast/core.hpp' file not found
#include <boost/beast/core.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[3/7] Building CXX object confget/CMakeFiles/confget.dir/confget.cc.o
FAILED: confget/CMakeFiles/confget.dir/confget.cc.o 
/Library/Developer/CommandLineTools/usr/bin/c++   -I/usr/local/include -I/home/luoxing/include -I/Users/didi/include -Wall -std=c++11 -Wall -std=c++1y -MD -MT confget/CMakeFiles/confget.dir/confget.cc.o -MF confget/CMakeFiles/confget.dir/confget.cc.o.d -o confget/CMakeFiles/confget.dir/confget.cc.o -c ../confget/confget.cc
../confget/confget.cc:5:10: fatal error: 'boost/network/protocol/http/client.hpp' file not found
#include <boost/network/protocol/http/client.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: cannot make progress due to previous errors.

**Comment by sgraham** [comment]
"ninja: build stopped: cannot make progress due to previous errors."

means that no other files can be built until some more succeed.

**Comment by nico** [comment]
Fixed by #1373
