### ISSUE TITLE
Alternative ninja file format based on arrays

### ISSUE THREAD

**Issue by jpakkane** [ninja-build/ninja#1084]
Currently the Ninja build definition files work on strings. That is, each command to invocate (as well as inputs and outputs) are strings that are assembled and then given to the system shell to execute. This causes a bunch of problems.

- need to worry about shell quoting
- win shell has a very small command line length which lead to response files (which may need different quoting)
- filenames with spaces and/or shell special characters cause problems

It would be nice (though admittably a fair bit of work) to get a different syntax for the Ninja file that deals natively with arrays similar to how Python's subprocess works. Ninja would also invoke all processes via `execve` or similar on posix platforms and whatever the corresponding Windows system call is to avoid having to deal with response files. The shell is never invoked (unless the user does it manually with `/bin/sh` or something) so the problem of quoting special character just goes away.

One backwards compatible way of doing this would be that the file is deemed to have the new syntax if the first declaration in it is this:

    ninja_file_format = newtype # or something similar

Then a rule might look like this:

    rule SOMETHING
     command = ['/path/to/someprog', '-o', '$out', '$in'] + ARGS

Whereas build steps would look like this:

    build ['output.o']: SOMETHING ['input.dat'] | ['somefile1', 'somefile2']
      ARGS = ['-something', '-other']

Note how all strings are quoted with a single '. This makes everything a lot less ambiguous.

**Comment by ogait87** [comment]
I think the **'$out'** in the examples should be **+ out +** since it can represent an array of files.

Since the idea is to create a new format, we could include environment variables in the rules block like this:
```
rule SOMETHING
  command = ['/path/to/someprog', '-o'] + out + in + ARGS
  enviroment = ['A=5'] + ENV

build ['output.o']: SOMETHING ['input.dat'] | ['somefile1', 'somefile2']
  ARGS = ['-something', '-other']
  ENV=['B=6']
```

**Comment by nico** [comment]
This was considered and rejected as it keeps the manifest format simpler and seems to work well enough. See also the last paragraph in the `## How to successfully make changes to Ninja` paragraph in HACKING.md.

**Comment by jpakkane** [comment]
If by manifest file you mean the dep manifest, it desperately needs support for multiple outputs at the same time. Fortran already requires this but more importantly Swift is invoked by running the compiler on all input files at the same time and then it outputs a bunch of .o files and a corresponding .d file for each. This is unsupportable with the current Ninja approach of only having one .d file per build rule.

And the current approach does not unfortunately work well enough. When you get characters that need to be quoted *and* a response file, things get unpleasant. See for example [here](https://groups.google.com/forum/#!topic/mesonbuild/5Y7ayDZKHEM).

**Comment by martine** [comment]
I think that maybe I should have done it this way, but it's probably too late to make such a fundamental change to Ninja.

And importantly, I would like to note that this change would not solve most of the problems you mention in the initial report.  Unfortunately, on Windows a command line is fundamentally a string and the parsing of that string into an argv array is done by code within each separate binary.  (You can read more about this in the "command lines" section of my blog post: http://neugierig.org/software/blog/2011/10/quoting.html ).  Even if Ninja used arrays for command lines, it would need to choose a way to serialize them into strings for Windows and you would still have response files and problems with special characters.

In fact, it's almost lucky that Ninja works with command lines as strings because it allows the Ninja generator program to control exactly what string is passed to the underlying program.  Depending on the program, the quoting rules may be different on Windows.

Regarding the problem in your generator with backslashes in -D flags, I remember also running into this problem for Chrome's build system.  It took some work but I eventually got it to work. It appears you also treated the command line as a plain string and replaced all the backslashes with forward slashes, but if you instead treated the command line as an array and did the proper replacements (as well as carefully read the command-line docs linked in the above post) you could make it work.

**Comment by martine** [comment]
It's been too long so I can't remember the code well, but I dug through the gyp git repo and found this change which sounds relevant to your meson problem:
https://codereview.chromium.org/668082

**Comment by martine** [comment]
Also this one is interesting.
https://chromiumcodereview.appspot.com/10408026

After my time.  Pretty crazy!

**Comment by jpakkane** [comment]
I'm have not done Windows development much (or at all really), but there are several pages on MSDN that describe process spawning functions that take arrays of strings. [Here's one for _spawnve](https://msdn.microsoft.com/en-us/library/1kkbefb8%28v=vs.100%29.aspx) that seems to do roughly what is described here. CreateProcess only takes a full string but that one does not. But dunno, maybe MS has screwed it up in other ways?

**Comment by martine** [comment]
spawn is a C library function.  It is implemented in terms of CreateProcess, which is the lower-level function and closer to a system call.  (Like how `fopen()` is a bunch of C code that makes use of `open()` which makes the actual system call on a Unix.)

**Comment by martine** [comment]
Here's another blog post that talks about how Windows commands lines work and how it has layers to make it behave in the way C expects, with argv arrays etc: http://blogs.msdn.com/b/twistylittlepassagesallalike/archive/2011/04/23/everyone-quotes-arguments-the-wrong-way.aspx
