### ISSUE TITLE
Ninja should probably support @rsp files on the command line

### ISSUE THREAD

**Issue by dpranke** [ninja-build/ninja#1355]
Way back in issue #53 we added support for response files as part of the ninja syntax.

However, we didn't actually add support for response files as input to ninja itself, e.g. `ninja -C out/Default @foo.rsp`. In Chromium builds, particularly when trying to build the pruned build graph that results from running `gn analyze` against the large build and the `all` target, you can get a list of targets back that easily exceeds Windows' max 8k command line length, and even exceeds the 128k Linux length.

I think we should probably just add support for rsp files here as well.

**Comment by evmar** [comment]
Another idea: gn could just emit the downstream-most targets?  (E.g. all the binaries?)

Total guess here, I haven no idea what gn actually does.  :)

**Comment by dpranke** [comment]
@evmar - it already does that.

**Comment by evmar** [comment]
Wow, that's a lot of binaries!

**Comment by dpranke** [comment]
it's not just binaries, unfortunately, for a lot of the java targets, we generate a bunch of auxiliary helper targets for each java_lib (e.g., run something through proguard, or emma, etc ...) and so you get an explosion of things :(.

**Comment by nico** [comment]
I thought about this for a bit. It's gnarly to implement since rsp quoting rules are platform dependent. (clang and lld for example have --rsp-quoting flags so you can pick if you want cmd.exe-style quote interpretation or posix quote interpretation). #53 just taught ninja to take a string and write it out; it doesn't need to know about the quoting.

I'd rather not add all this complexity to ninja. If you really need to pass a super long list of targets to ninja, you can append `build build_rsp: phony $contents` to the bottom of your build.ninja and ask ninja to build target "build_rsp".
