### ISSUE TITLE
Build stats

### ISSUE THREAD

**Issue by Leandros** [ninja-build/ninja#1374]
Would be great if ninja could generate stats, similar to [FASTBuild](http://fastbuild.org/docs/options.html#report), when `-report` is passed.

This report includes:

- how ninja was invoke, which target was build and which arguments were passed
- the time it took to build the current target
- the time it took to build each object file

This provides valuable information about the build, and can be used to optimize build time.

Attached is an example report of a project I'm working on:
[report.html.zip](https://github.com/ninja-build/ninja/files/1638818/report.html.zip)

**Comment by atetubou** [comment]
I use https://github.com/nico/ninjatracing to see build stats from ninja_log.

**Comment by Leandros** [comment]
That looks incredibly useful! Thank you!

**Comment by randomascii** [comment]
ninjatracing is very useful however my preferred option is to use my experimental script that can be found here:

https://chromium-review.googlesource.com/871988

This produces a brief text summary of the build, listing the slowest build steps and a summary by output type. It is intended to be appropriate for hooking up as an automatic post-build step, giving a compact summary in the console window.

Both tools work by looking at the .ninja_log file which is a fairly simple format that records task lengths and overlap.

One feature which my script has which I haven't seen elsewhere is the idea of "weighted time" which is elapsed-time divided by how many tasks were running. Thus, it gives a sense of how much a build step "matters". A step that takes 30 s but runs in parallel with 1,000 other steps is irrelevant. That same step running alone - serializing the build - is a huge issue. "weighted time" captures that.

**Comment by csagan5** [comment]
@randomascii that script is missing the shebang `#!/usr/bin/python2` and gives me:
```
    Longest build steps:
          12.3 weighted s to build (154 items) android_clang_arm/gen/chrome/generated_resources_stamp.d.stamp, android_clang_arm/gen/chrome/grit/generated_resources.h, ... (36.8 s CPU time)
          19.8 weighted s to build gen/components/resources/about_credits.html (59.3 s CPU time)
          24.7 weighted s to build android_clang_arm/obj/chrome/browser/browser/chrome_content_browser_client.o (74.2 s CPU time)
          27.2 weighted s to build android_clang_arm/obj/chrome/browser/safe_browsing/safe_browsing/data_reduction_proxy_resource_throttle_android.o (81.7 s CPU time)
          30.0 weighted s to build android_clang_arm/obj/chrome/browser/safe_browsing/safe_browsing/ui_manager.o (90.1 s CPU time)
          31.0 weighted s to build gen/chrome/android/monochrome_public_apk/classes.dex (71.1 s CPU time)
          90.3 weighted s to build (5 items) gen/chrome/android/monochrome_public_apk/monochrome_public_apk.proguard.jar, gen/chrome/android/monochrome_public_apk/monochrome_public_apk.proguard.jar.flags, ... (271.0 s CPU time)
          98.3 weighted s to build (4 items) android_clang_arm/gen/chrome/resources_stamp.d.stamp, android_clang_arm/gen/chrome/grit/browser_resources.h, ... (295.0 s CPU time)
          98.5 weighted s to build gen/arsc/apks/MonochromePublic.ap_ (295.6 s CPU time)
         179.2 weighted s to build (4 items) libmonochrome.so, libmonochrome.so.TOC, ... (537.6 s CPU time)
Traceback (most recent call last):
  File "./post_build_ninja_summary.py", line 289, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./post_build_ninja_summary.py", line 282, in main
    SummarizeEntries(entries)
  File "./post_build_ninja_summary.py", line 250, in SummarizeEntries
    extension = GetExtension(target)
  File "./post_build_ninja_summary.py", line 164, in GetExtension
    assert(extension == extension.lower() or extension == '.TTF')
AssertionError
```

I checked ninjatracing and I do not enough information yet. What I am trying to get is (apparently simple): the count of edges that you would have from a build from scratch, but while already running an incremental build. Is that even possible?

So for example:
1. you start a build, get halfway
2. stop it, start it again
3. what was the total count of edges at (1), thus including those already built?

**Comment by randomascii** [comment]
That error with the extension check was fixed in a later revision. The latest version of the script is checked in. You can see it at:
https://cs.chromium.org/chromium/tools/depot_tools/post_build_ninja_summary.py

The post_build_ninja_summary.py script and ninjatracing (see link above) both scan the .ninja_log file, which contains start/stop times about every build, not just the latest incremental build. By default these scripts throw away all of this information except for that from the latest incremental build. ninjatracing has an option to include all of the information.

It would be easy enough to add other options, such as generating a separate report for every partial build that was done (two different build invocations in your scenario). It's less clear whether it would be generically useful but if you make such modifications to post_build_ninja_summary.py and want them in the depot_tools version then create a CL and CC brucedawson@chromium.org.

This is the line that recognizes a new build invocation and throws away the previous results:

https://cs.chromium.org/chromium/tools/depot_tools/post_build_ninja_summary.py?l=139

**Comment by csagan5** [comment]
@randomascii thanks for the pointers, I totally missed out. I see the script has made progress since then, I will give a look.

**Comment by nico** [comment]
Sounds like existing tooling works fine here.
