### ISSUE TITLE
Ninja does not recognize browse as a tool, despite it being mentioned in the manual

### ISSUE THREAD

**Issue by Kazark** [ninja-build/ninja#1478]
I don't know if this is a case of the [extra tools](https://ninja-build.org/manual.html#_extra_tools) section of the manual being out of date, or me misunderstanding/doing something wrong, or a bug in Ninja, but when I issue the command

    ninja -t browse

I get:

    ninja: fatal: unknown tool 'browse'

This is running Ninja 1.8.2 on Windows 7, installed by extracting from the zip downloaded from GitHub. All the other tools listed in that section of the manual are recognized.

The description of this command is schnazzy so if it's available I'd like to try it out. If it's not available, how do we update the manual?

**Comment by sgraham** [comment]
It's just not supported on some platforms https://github.com/ninja-build/ninja/blob/ca041d88f4d610332aa48c801342edfafb622ccb/configure.py#L107 . I think not for any major reason, but browse.cc looks like it might need a little futzing to work on Windows. Otherwise, yeah, we could update https://github.com/ninja-build/ninja/tree/master/doc to mention that lack.

**Comment by Pwera** [comment]
To enable browser mode `configure.py` needs to append `-DNINJA_HAVE_BROWSE` flag.
After that this command fails:
`".\src\inline.sh" kBrowsePy < .\src\browse.py > build\browse_py.h`

Content of inline.sh
```
varname="$1"  
echo "const char $varname[] ="
od -t x1 -A n -v | sed -e 's|[ \t]||g; s|..|\\x&|g; s|^|"|; s|$|"|'
echo ";"
```
`od` command is also working on `mingw` platform.
Can someone explain those steps here?

**Comment by Kazark** [comment]
@jhasse Thanks
