### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [ninja-build/ninja#1659]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by jhasse** [comment]
I'm waiting for #1526 (or another CI solution), otherwise it's too troublesome for me to build on all three platforms.

Also have a look at the milestone for the next release to get an idea what is missing: https://github.com/ninja-build/ninja/milestones/1.10.0

**Comment by nightlark** [comment]
I have an alternative to #1526 that should work starting Nov 13 if you're not set on using that Azure Pipelines setup.

**Comment by jhasse** [comment]
Care to elaborate?

**Comment by nightlark** [comment]
GitHub Actions will become available to all repositories on Nov 13 -- it supports cross-platform builds and is pretty similar to Azure, except it makes interacting with the GitHub API much easier and has 20 concurrent jobs instead of 10.

A workflow similar to https://github.com/nightlark/ninja/blob/release-ninja-binaries/.github/workflows/release-ninja-binaries.yml could be used to build binaries on Windows/macOS/Linux for each commit (with the binaries available for download as artifacts), along with uploading the binaries as assets when releases are published.

After making a release on GitHub within a few minutes binaries for the 3 platforms will be uploaded, the end result looking like this https://github.com/nightlark/ninja/releases

**Comment by jhasse** [comment]
Sounds awesome! Thanks for the info. I guess one still needs to be the owner of the repository to activate it.

(btw: Ubuntu shouldn't be the latest version so that the binary runs on older distributions)

**Comment by jhasse** [comment]
@nightlark Seems that GitHub Actions is live. Can you create a PR? :)

**Comment by nightlark** [comment]
Yea, I'll create a PR.
