### ISSUE TITLE
Pick up CMake flag VS_DPI_AWARE when building windows application

### ISSUE THREAD

**Issue by RadMap** [ninja-build/ninja#1673]
It appears that Ninja does not pick up the CMake flag VS_DPI_AWARE (new since CMake 3.16) when building a windows application. Is this the intended Ninja behavior or will this flag be a valid configuration building with Ninja in the future?

**Comment by jhasse** [comment]
This looks more like a CMake bug to me?

**Comment by RadMap** [comment]
For reference: The flag is working properly building with Visual Studio generator. Maybe it is my lack of knowledge in how Ninja works?

**Comment by jhasse** [comment]
Well, you're talking about the Visual Studio generator *of CMake*. Ninja itself doesn't care much about any flags and if they are passed to the compiler completely depends on the generator.

**Comment by Katharsas** [comment]
The problem is that all CMake `VS_` flags are VS-only flags in general (so only applied to .vsproj generation), see https://gitlab.kitware.com/cmake/cmake/-/issues/19960

So i guess the problem ist that there is no general agreed on way how to set dpi awareness for windows independent of generator. So i guess currently the official way to set DPI awareness with Ninja is to provide a custom Manifest file, is that correct?
