### ISSUE TITLE
How to uninstall a package installed with sudo ninja install? 

### ISSUE THREAD

**Issue by mrgransky** [ninja-build/ninja#1714]
I installed a package from source with `ninja` build system as follows:

    $ git clone https://github.com/google/protobuf.git
    $ cd protobuf
    $ git checkout tags/${VERSION}
    $ mkdir build
    $ cd build
    $ cmake -G Ninja \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -Dprotobuf_BUILD_TESTS=OFF \
      ../cmake
    $ ninja
    $ sudo ninja install

and I believe it is installed in `/usr/local/bin/` since:

`$ which protoc` :  `/usr/local/bin/protoc` and `$ /usr/local/bin/protoc --version` gives me: `libprotoc 3.4.0`

My question is how to uninstall a package when installed with `sudo ninja install` when the option `sudo ninja uninstall` does not exist in this case?

**Comment by jhasse** [comment]
CMake creates the install target. So you need to ask CMake devs why there's no uninstall target.

**Comment by mrgransky** [comment]
so there's no way to deal with such situation?

**Comment by jimon** [comment]
Yes it has nothing to do with ninja, you could ask the same about make - why no uninstall target in make?

CMake doesn't provide one because it's too risky to wipe random files from your system.

But if you want to try, when you invoke install target, it should create a file listing all touched files, so `xargs rm < install_manifest.txt` should do.

**Comment by wachin** [comment]
Thanks, working for my

**Comment by solomoncyj** [comment]
how about meson?

**Comment by iTrooz** [comment]
Here is a version that should work on files with spaces: `cat install_manifest.txt | xargs -n1 -d "\n" rm`
