### ISSUE TITLE
clang doesn't print colored diagnostics when invoked from ninja

### ISSUE THREAD

**Issue by nico** [ninja-build/ninja#174]
The reason for this is that ninja sets subprocess stdout/stderr to a pipe (Subprocess::Start(), subprocess.cc), and clang checks if StandardErrHasColors() (tools/clang/lib/Driver/Tools.cpp), which is false if !isatty(2) (lib/Support/Unix/Process.inc).

I looked around a bit, and the way to do this seems to be to call fork_pty() to run the child in a pseudo terminal. I don't know if this would impact subprocess creation time, and if opening ~4000 pseudo ttys (a chrome build at -j10000) is considered good form.

(It's possible to force clang to always emit color escaped codes using "-Xclang -fcolor-diagnostics", but that's pretty hacky. make doesn't seem to override stderr on unix as far as I can tell, child_execute_job() in job.c)

**Comment by CatalinMustata** [comment]
Many years later, I'm confused about how this is supposed to work... because it's not working on my configuration. My CMake compile options are like so:
`set_property(DIRECTORY APPEND PROPERTY COMPILE_OPTIONS $<$<COMPILE_LANGUAGE:C>:-Wimplicit-int -Wimplicit-function-declaration -Wno-gnu-zero-variadic-macro-arguments -std=c11>  -Xclang -fcolor-diagnostics)`

No colored output is available unfortunately (MacOS, iTerm2 with zsh). And I've checked the output, the flags do get added to the compile options at runtime. If I switch Ninja with Make, all is well.

**Comment by jhasse** [comment]
Try `-fdiagnostics-color`. Are you running ninja in a terminal?

**Comment by CatalinMustata** [comment]
Sorry, I didn't specify I'm using clang. That flag is for gcc.

**Comment by Timmmm** [comment]
So as I understand it, Clang detects if it is outputting to a terminal and enables colours automatically in that case. Ninja captures Clang's output so Clang things it isn't outputting to a terminal.

So you have to force Clang to output colours with `-fdiagnostics-color=always` (or `-fcolor-diagnostics` for GCC - yeay consistency). But then that means that when Ninja is outputting to something that isn't a terminal (e.g. Emacs) that program gets confused by the colour codes.

And your "solution" was to have Ninja strip the colour codes if it is not outputting to a terminal.

So Ninja knows if it is meant to output colours. It can "tell" Clang whether it should output colours (by pretending to be a terminal). But instead it throws that information away and forces the user to set `-fdiagnostics-color` manually?

That seems like a bad solution. Why can't Ninja just do something like this:

```
if (output_is_terminal) {
   use_pseudo_terminal = true;
}
```

[Clang uses `istty()`](https://github.com/llvm/llvm-project/blob/master/llvm/lib/Support/Unix/Process.inc#L277) on Unix and [`GetConsoleMode()` on Windows](https://github.com/llvm/llvm-project/blob/master/llvm/lib/Support/Windows/Process.inc#L286) to determine if the output is a console.

So you can just create the subprocess in a pseudo-terminal instead (`openpty()` on Linux, not sure about Windows).

The only downside I can see is that you can't get `stdout` and `stderr` separately from `openpty()`.  There is a question about doing that on StackOverflow but [the only solution](https://stackoverflow.com/a/34189559/265521) uses a dirty `LD_PRELOAD` hack. However it seems like Ninja doesn't distinguish between them anyway.

**Comment by Timmmm** [comment]
I did find this mentioned [in the wiki](https://github.com/ninja-build/ninja/wiki/FAQ):

> Ninja could use pseudo ttys to work around this further, but different systems have different limits on the number of ptys available. I also worry that commands like svn up would assume they can interact with the user.

**Comment by jhasse** [comment]
Yeah, using a pseudo tty is overkill when the only thing you want is color codes. See https://bugs.llvm.org/show_bug.cgi?id=23609 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80271 for a possible solution.

**Comment by david-fong** [comment]
For CMake users, CMake 3.24 ([which looks like it releases on June 15th?](https://gitlab.kitware.com/cmake/cmake/-/milestones/102#tab-issues)) will have [`CMAKE_COLOR_DIAGNOSTICS`](https://cmake.org/cmake/help/git-stage/envvar/CMAKE_COLOR_DIAGNOSTICS.html). Here's their [issue thread](https://gitlab.kitware.com/cmake/cmake/-/issues/15502) where the feature was discussed.

[Here's a link to a comment in the thread](https://gitlab.kitware.com/cmake/cmake/-/issues/15502#note_1134762) by Craig about how the feature might be best used due to some IDEs not supporting ansi escape coloring- the environment variable allows per-user config.

**Comment by mohkale** [comment]
Hi there,

Even with the latest CMake and ninja release I don't get colorised output when building with -DCMAKE_COLOR_DIAGNOSTICS=On. 

```text
$ cmake --version
cmake version 3.30.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ ninja --version
1.12.1

$ gcc --version
gcc (GCC) 14.2.1 20240805
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If I set the `CLICOLOR_FORCE=1`  in the environment running the CMake build then I do get output. Just sharing for anyone else that stumbles on this.

FYI: This doesn't cause CMake itself to colorize the output like it does in Make. So the `[x%] build target` outputs won't be colorised. But the build-tool/compiler output will be.

**Comment by jhasse** [comment]
In what kind of terminal simulator are you running ninja?

**Comment by mohkale** [comment]
Tmux within [suckless terminal](https://github.com/mohkale/st/tree/3e4786ef95e137fe6957ab81e0fb61bf1dcb013d). I'm also using a [custom terminfo](https://github.com/mohkale/dotfiles/tree/master/prog/tmux/term) definition that adapts the combines the sequences supported by tmux and st. To be clear color does work when I run CMake/Ninja into a tty but if I put a pager in front of it like cat then color is suppressed unless I add that CLICOLOR_FORCE option.

Example for with and without:

![Screenshot_20240907_143851](https://github.com/user-attachments/assets/f850d228-ea67-4836-9349-c9c5b908b5a0)

![Screenshot_20240907_143754](https://github.com/user-attachments/assets/aceb6138-1f14-46e3-84b5-0f3f89fdc41a)

In both cases the -fdiagnostics-color=always option is passed to gcc. I'd wager ninja is probably stripping it out but I haven't investigated that far yet :thinking:.

**Comment by jhasse** [comment]
Yes, see https://github.com/ninja-build/ninja/wiki/FAQ#why-does-my-program-with-colored-output-not-have-color-under-ninja

**Comment by mohkale** [comment]
I think that wiki page should also mention you can prevent ninja escaping color output by setting that env variable.

> Ninja itself will detect if it's writing to a terminal and escape color codes from commands if it isn't.

Also I don't really follow the reasoning for this. Its one thing to explicitly pass a flag to tools to enable color in environments that ordinarily wouldn't have it but needing to pass another different flag to ninja to prevent it overriding that choice is a bit odd. I guess there's a uniformity aspect to the output but really I think ninja should defer to the tools it runs instead of deciding for them. This might make more sense if output from ninja was colored. Like task descriptions. But as of now I don't think that's supported.

**Comment by jhasse** [comment]
The compiler would behave in the same way when invoked directly, that's the reasoning ;)

**Comment by mohkale** [comment]
When invoked directly the compiler would print color... unless I'm misunderstanding. If I just run the command that ninja is doing directly and pipe to cat it still has color.

![Screenshot_20240912_191514](https://github.com/user-attachments/assets/a93ec3b9-eab2-4ba9-9367-5d882d2f4f63)

On the hander if I stop setting the CMake option that passes the compiler option that enables color but do still supply the CLI_COLOR force env variable then I no longer get color regardless of if I'm writing to a terminal or not.

![Screenshot_20240912_191722](https://github.com/user-attachments/assets/ca626895-abd5-485f-bcf8-9937f6d5da0c)

I think what I dislike about the current behaviour is it's an override of an override. If gcc respected CLICOLOR_FORCE I'd disagree but adding support is still missing and the interim you need to both set CLI_COLOR and pass compiler options to get color working with ninja :disappointed:.

**Comment by jhasse** [comment]
I mean without `-fdiagnostics-color=always` the compiler will not print color codes when it gets piped into cat. So ninja wants to mimic that, but it's kinda hard since the compiler is ALWAYS piped when ninja executes it. And ninja doesn't (and IMHO shouldn't) know/parse the flags passed to the compiler.

You're right that `-fdiagnostics-color` is a non standard way and it would be better if GCC used the same environment variable instead. You can raise your support for that here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80271

**Comment by eli-schwartz** [comment]
> You're right that `-fdiagnostics-color` is a non standard way and it would be better if GCC used the same environment variable instead. You can raise your support for that here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80271

Environment variables are significantly more nonstandard than -fdiagnostics-color, but perhaps you meant that GCC should add support for `--color={always|auto|never}`?

**Comment by jhasse** [comment]
> Environment variables are significantly more nonstandard [...]

Huh why? There's a standard set of environment variables and there's a standard set of command line flags.

> Note that CLICOLOR_FORCE is a nonstarter since setting it will break the ls program on some operating systems, [...]

Can you elaborate?

**Comment by dmiller423** [comment]
A bit of necroed response, however I thought it would be useful for people hitting this as a search result.

To use ninja+clang in windows terminal / cmd.exe you must also pass `-fansi-escape-codes` for colored output to pass through.  
(This also affects IDE's such as CLion)
