### ISSUE TITLE
When set compiler to /bin/clang++-10, ninja always rebuild target that has no change

### ISSUE THREAD

**Issue by zyd2001** [ninja-build/ninja#1775]
I'm using CMake with Ninja and I found a strange behavior. I have only installed clang-10 and it has many symlinks. When I set the compiler to /bin/clang++ or /bin/clang++-10, every time I try to build using cmake command, all dependent target, no matter changed or not will be rebuilt. But if I set the compiler to any symlink or the real binary besides /bin/clang++ or /bin/clang, there will be no problem.

**Comment by jhasse** [comment]
Can you try `ninja -d explain`?

**Comment by zyd2001** [comment]
my test file is 
```cpp
#include <iostream>
int main() {}
```
And it's my CMakeLists.txt
```
project(test)
add_executable(main test.cpp)
```
The generated `rules.ninja` and `build.ninja`
[files.zip](https://github.com/ninja-build/ninja/files/4600447/files.zip)

The output of `ninja -d explain`
[output.txt](https://github.com/ninja-build/ninja/files/4600429/output.txt)

If I set compiler to `/bin/clang++`, the output is always this, but if I set to `/usr/bin/clang++`, only the first time run will have this output

**Comment by ilyapopov** [comment]
Does the file `/include/c++/9/iostream` exist on your machine? If not, what is the actual path to that header (maybe `usr/include/c++/9/iostream`?)

**Comment by zyd2001** [comment]
Yes, the actual path is `/usr/include/c++/9/iostream`. The `/include` directory doesn't exist

**Comment by ilyapopov** [comment]
So far it looks like this is clang reporting wrong paths for dependencies. Just one more test for confirmation: what's the output of `ninja -t deps`? Does it contain correct or incorrect paths to include files?

**Comment by zyd2001** [comment]
It contains both `/inlcude` and `/usr/include`.

**Comment by jhasse** [comment]
Looks like #1330 and #1400 to me. Please re-open if you think otherwise.

**Comment by starcatter** [comment]
Commenting here because I just encountered the same issue (not sure if CMake or Ninja is to blame) on Ninja 1.11.1 on Manjaro Linux: 
* Setting CMake compiler to `-DCMAKE_C_COMPILER=/bin/clang -DCMAKE_CXX_COMPILER=/bin/clang++` results all project files being rebuilt, regardless of changes. 
* Setting CMake compiler to `clang` and `clang++` made Ninja only build modified files and otherwise give the `ninja: no work to do.` message

Notes:
* to be specific, it seems not **all** files are always rebuilt. However out of initial 1513 files, 1487 are being rebuilt.
* changing compiler paths to `/usr/bin/clang` and `/usr/bin/clang++` also fixed the problem.

`$ ls -la /bin/clang` -> `lrwxrwxrwx 1 root root 8 11-19 22:17 /bin/clang -> clang-14`
`$ ls -la /usr/bin/clang` -> `lrwxrwxrwx 1 root root 8 11-19 22:17 /usr/bin/clang -> clang-14`
`$ ls -la /usr/bin/clang++` -> `lrwxrwxrwx 1 root root 5 11-19 22:17 /usr/bin/clang++ -> clang`
`$ which clang` -> `/usr/bin/clang`
`$ which clang-14` -> `/usr/bin/clang-14`

**Comment by mrpink17** [comment]
> * Setting CMake compiler to `clang` and `clang++` made Ninja only build modified files and otherwise give the `ninja: no work to do.` message

Thanks!! This is still an issue
ninja 1.12.1
cmake 3.31.3
