### ISSUE TITLE
ninja destroys dependency files after created by compiler

### ISSUE THREAD

**Issue by Code7R** [ninja-build/ninja#1981]
![ninja_killing_depfiles_anon](https://user-images.githubusercontent.com/10660264/121347420-77750f80-c927-11eb-8811-49c0342110b5.png)
Version: 1.10.2
OS: Windows 10 x64

Usage type:
cmake-generated ninja configuration
custom compiler and custom cmake toolchain file
the compiler creates dep files (parameter of the compiler)
resulting depfiles are referenced via rule definition in CMakeFiles/rules.ninja as "depfile = $DEP_FILE"
s.
So far, that worked fine on a few systems. But on one PC, strange things happen. The changes of headers stop triggering the build, and the closer investigation shows that for unknown reason, the depfiles (*.obj.d) are not there. Deeper look with procmon shows that apparently ninja sets some flag on the file descriptor after reading those dep files, then they are removed by OS.

Unfortunately, the lifecycle of depfiles is not properly explained in the manual. I have found "-d keepdepfile" option by looking around, which indicated that they are removed deliberately. But why? Does this assume that compiler will recreate them?If so, fine, but then it should move the existing file reliably out of the way prior to calling the compiler. At the moment, I see the deleting action happen around the end of the compiler execution.

If the assumption is correct, this smells like a bug. Either some race condition, or some refcounting issue (which makes the old handle not be closed in time).

AFAICS, the only special thing about the system where it happens is that it's a 16 core system with a high single-thread performance.

Maybe ninja should rename the dep files first and only them remove them and only then call the compiler?

**Comment by jhasse** [comment]
I bet this is an anti-virus issue. Windows sucks so much you have resort to hacks when you want to delete files.

**Comment by digit-google** [comment]
Ninja removing depfiles by default is an intentional feature.

The depfiles are read by Ninja, and their content is then appended to the .ninja_deps file (called the deps log) in an efficient binary format that is much faster to load on the next invocation (I believe this was motivated by the fact that opening thousands of small files on Windows is very slow compared to other systems).

You can use the "deps" tool (e.g. `ninja -t deps`) to print the content of the deps log if you want.
And the `-d keepdepfile` option prevent their removal for manual inspection.

I suggest opening a new issue describing what your real problem is (i.e. "the change of headers stopping triggering the build"), with a simple recipe to reproduce the problem.

**Comment by Code7R** [comment]
@jhasse was probably right. The issue is no longer reproducible with the current Ninja version and Windows 20H2 or newer.

Closing for now, please reopen if needed.
