### ISSUE TITLE
Ninja doesn't forward environment variables to `meson` on regeneration

### ISSUE THREAD

**Issue by nazar-pc** [ninja-build/ninja#1997]
I have a project where I install meson and ninja into specific location to make it independent of environment:
```
python3 -m pip install --target=out/pip meson ninja
```

Then I do usual stuff like `meson setup` and `meson compile` with `PYTHONPATH=out/pip` and it works.

The problem happens when I edit `meson.build`, in this case `ninja` tries to regenerate project and fails:
```
[0/1] Regenerating build files.
Traceback (most recent call last):
  File "/web/github/mediasoup/worker/out/pip/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
FAILED: build.ninja 
/web/github/mediasoup/worker/out/pip/bin/meson --internal regenerate /web/github/mediasoup/worker /web/github/mediasoup/worker/out/Release --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

Calling this works:
```
PYTHONPATH=out/pip /web/github/mediasoup/worker/out/pip/bin/meson --internal regenerate /web/github/mediasoup/worker /web/github/mediasoup/worker/out/Release --backend ninja
```

So I make a conclusion that there is something wrong with `ninja` here.

UPD: Workaround is to call `meson setup --reconfigure` first just in case.

**Comment by jhasse** [comment]
Is `PYTHONPATH=out/pip` set when you call ninja?

**Comment by nazar-pc** [comment]
To the best of my knowledge yes: https://github.com/versatica/mediasoup/blob/ff17d135957513aff86d45d99e82ffce45187318/worker/Makefile#L33-L40
The call in Meson I saw a while ago was forwarding environment variables too.

**Comment by jhasse** [comment]
Hm ... ninja does forward environment variables so maybe something else is going on:

```
rule foo
  command = python -c "import os; print(os.getenv('PYTHONPATH'))"

build foo: foo
```

```
$ env PYTHONPATH=bar ninja
[1/1] python -c "import os; print(os.getenv('PYTHONPATH'))"
bar
```

**Comment by nazar-pc** [comment]
I'm not 100% whose fault is it, the issue on happens on reconfiguration. In other cases environment variables are set properly.

**Comment by jonesmz** [comment]
Are you able to construct a minimal reproduction that reproduces the problem? E.g. a zip file containing a ninjafile and script that when run demonstrates the issue.

**Comment by nazar-pc** [comment]
I'm only a user of Ninja by proxy. While theoretically I can do that, I'm quite busy to dedicate time doing this right now.
It is easily reproducible and I'm using `meson setup --reconfigure` as a workaround for now: https://github.com/versatica/mediasoup/blob/150bba4eec122824975f6e18bfc60dd7b6f40228/worker/Makefile#L85-L105

**Comment by digit-google** [comment]
As stated previously, Ninja already passes its parent environment to its sub-processes, including the command used to regenerate the build plan, so it looks like the issue is that PYTHONPATH is not properly passed to Ninja, if it is really set before invoking it.

Can you do the following experiment to verify that: after running meson, edit  the `build.ninja file` to prefix `echo " 
"PYTHONPATH=[$PYTHONPATH]" && ` to the command that invokes meson to regenerate the build plan. This will dump the value of PYTHONPATH to stdout before running the command. Brackets are used here to detect unexpected newlines in the value.

You should also print the value in line 73 of your Makefile to verify that it is properly defined before invoking Meson.

**Comment by ibc** [comment]
> edit the `build.ninja file` to prefix `echo " "PYTHONPATH=[$PYTHONPATH]" && ` to the command that invokes meson to regenerate the build plan.

Can you specify how to do this? `meson.build` is regenerated every time I call the meson command:

```
meson setup --prefix "{MEDIASOUP_INSTALL_DIR}" --bindir "" --libdir "" --buildtype release -Db_ndebug=true -Db_pie=true -Db_staticpic=true --reconfigure {MESON_ARGS} "{BUILD_DIR}"'
```

And where in `meson.build` should I add that `echo`? Within the `rule REGENERATE_BUILD` rule? Something like this?

```
rule REGENERATE_BUILD
 command = echo "PYTHONPATH=[$PYTHONPATH]" && /Users/ibc/src/v3-mediasoup/worker/out/pip_meson_ninja/bin/meson --internal regenerate /Users/ibc/src/v3-mediasoup/worker .
```

**Comment by digit-google** [comment]
I meant the following for this experiment: Run Meson once, then edit the `build.ninja` manually, then run `ninja` directly.
I.e. no need to run Meson more than once yourself, and no need to edit a Meson file.

Apart from that, the `REGENERATE_BUILD` command seems the right place.

**Comment by nazar-pc** [comment]
The fact that `meson` calls `ninja` internally is a bit orthogonal though. We always call `meson` commands and never interact with `ninja` directly.

**Comment by digit-google** [comment]
Yes, that's why this is an experiment, to validate the value that PYTHONPATH value that Meson passes to Ninja. This information will help us understand what is going on, and whether this is a Ninja or a Meson issue (I strongly suspect the latter, but it's always better to check). I also recommend posting an issue on the Meson bug tracker, if you haven't done so.

**Comment by nazar-pc** [comment]
Can't reproduce with latest Meson version, closing
