### ISSUE TITLE
Update `ninja-build` version 1.10.0 on Ubuntu Focal

### ISSUE THREAD

**Issue by Splines** [ninja-build/ninja#2298]
I just wanted to install Ninja 1.11 for C++20 modules to work with CMake. However, on _Ubuntu 20.04.6 LTS_ (Codename: focal), the latest available package is
```
1.10.0-1build1: amd64 arm64 armhf i386 ppc64el riscv64 s390x
```

see [here](https://packages.ubuntu.com/search?keywords=ninja-build&searchon=names&suite=focal&section=all) (site takes a bit before responding). That's why I kindly ask to upgrade the version over there. (I don't know what the usual flow of information is for publishing apt packages, but I assume it's on `ninja`'s side to push it to the repository storing apt packages).

Meanwhile, I will have to build from sources...

**Comment by eli-schwartz** [comment]
> That's why I kindly ask to upgrade the version over there. (I don't know what the usual flow of information is for publishing apt packages, but I assume it's on `ninja`'s side to push it to the repository storing apt packages).

Unfortunately, no.

The Ubuntu developers are the only people with the ability to publish new apt packages for ninja -- developers of the software itself have zero power over this.

Even more unfortunately, Ubuntu 20.04 LTS is, in fact, an LTS release. LTS means that Ubuntu will never update any software to new versions, because updating software to new versions introduces new features and possibly new bugs, and can be a breaking change to LTS users whose workflows are interrupted. If there's a critical security vulnerability in some software, they will carefully backport a tiny patch to the old version.

This is why LTS distros exist. If you want new versions of software, your options are to switch to a different distro or use the Ubuntu "mantic" development branch or something.

**Comment by Splines** [comment]
@eli-schwartz Ok, thanks for the clarification, didn't know about this (unfortunate but somewhat reasonable) policy on the part of Ubuntu.
