### ISSUE TITLE
Unbreak highly-parallel builds

### ISSUE THREAD

**Issue by fischman** [ninja-build/ninja#233]
Running ninja with -j5000 dies at ToT like this:
ninja: FATAL: pipe: Too many open files

Culprit seems to be: 0eebd5fe1dec021a63110ecab8fa411f9980745f
(note there's no error in the build, and no ctrl-c'ing going on)

The shell in question has a ulimit -n of 32k (and builds -j5000 just fine at the previous commit).

**Comment by thiagomacieira** [comment]
FreeBSD and OpenBSD have `ppoll`: https://www.freebsd.org/cgi/man.cgi?poll & https://www.freebsd.org/cgi/man.cgi?query=poll&manpath=OpenBSD+7.1
NetBSD has `pollts` with the same semantics: https://www.freebsd.org/cgi/man.cgi?query=poll&manpath=NetBSD+9.3

Darwin (macOS) has neither, but since doing distributed compilation on macOS is hard enough by itself, Mac users can live with the 1024 file descriptor limitation.
