### ISSUE TITLE
`-k 0` but `cannot make progress due to previous errors` 

### ISSUE THREAD

**Issue by yuanfang-chen** [ninja-build/ninja#2339]
I thought `-k 0` should finish the build regardless. But I still get
`ninja: build stopped: cannot make progress due to previous errors`. Is this expected behavior? Thank you!

**Comment by eli-schwartz** [comment]
What part of the build should it finish?

The error message is saying that it attempted to build every part of the build. Some targets failed to build, and other targets take a failed target as ***input*** so they failed to even start, but every other target was built.

Then it exited with a failure message because some things errored out.

**Comment by yuanfang-chen** [comment]
Thanks for the explanation. I think that's what happened. Closing..
