### ISSUE TITLE
Depfiles generated by intel's icx on windows are not processed correctly.

### ISSUE THREAD

**Issue by borg323** [ninja-build/ninja#2353]
I'm attaching a depfile geenrated during the build that results in no dependencies.
[src_version.cc.d.txt](https://github.com/ninja-build/ninja/files/13319183/src_version.cc.d.txt)

**Comment by digit-google** [comment]
Can you provide more details here? What does "not processed correctly" means? Some dependencies are missing from the deps log, or all of them, Ninja errors or something else?

For example, can you also provide the result of `rm .ninja_deps version.o && ninja -d keepdepfile version.o && ninja -t deps version.o` to see what was actually generated and recorded?

**Comment by borg323** [comment]
The project builds correctly, but no dependencies are recorded (except the corresponding source file). The output of `ninja -t deps lc0.exe.p\src_version.cc.obj` (I had already used keepdepfile in the last build) is:
```
lc0.exe.p/src_version.cc.obj: #deps 0, deps mtime 7213205122140025 (VALID)
```

**Comment by digit-google** [comment]
Thank you. I attached a tiny build plan to try to reproduce the issue,

[build-2353.zip](https://github.com/ninja-build/ninja/files/13319852/build-2353.zip)

In a nutshell, a fake compile command for ../src/version.cc copies the depfile you uploaded to the build directory and passes that as the `depfile` argument. Also `deps = gcc` is used to ensure the result is recorded into the deps log (otherwise, the depfile will be read on each Ninja invocation, never removed, and never copied into the log).

Or in other words:

```
rule fake_compile
  command = touch $out && cp ../version.o.d $out.d
  depfile = $out.d
  deps = gcc

build version.o: fake_compile ../src/version.cc
```

I am on Linux right now, and I see that the depfile's content is properly recorded in the deps log, i.e.:

```
$ cd build-2353/out && ninja version.o && ninja -t deps version.o
[1/1] touch version.o && cp ../version.o.d version.o.d
version.o: #deps 88, deps mtime 1699623681970503493 (VALID)
    ..\src\version.cc
    ..\src\version.h
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstdint
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\sal.h
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\concurrencysal.h
    C:\PROGRA~2\Intel\oneAPI\compiler\latest\windows\lib\clang\17\include\vadefs.h
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vadefs.h
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h
    C:\PROGRA~2\Intel\oneAPI\compiler\latest\windows\lib\clang\17\include\stdint.h
    ...
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\tuple
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cctype
    C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt\ctype.h
    ..\src\version.inc
    build_id.h
```

Can you take a look at your build plan and show the exact build statement for version.o, as well as the definition of the rule that it invokes?

**Comment by borg323** [comment]
Thanks, this helped me find the actual problem. I had to edit it a bit to work on windows, but the dependencies are recorded correctly, the actual problem was a small difference in the depfile name that I didn't notice.
