### ISSUE TITLE
clang-tidy CI way too slow

### ISSUE THREAD

**Issue by jhasse** [ninja-build/ninja#2446]
Our GitHub Action that runs clang-tidy takes way too much time. Something can't be right there?

**Comment by digit-google** [comment]
According to https://stackoverflow.com/questions/76531831/why-is-clang-tidy-in-clangd-so-much-faster-than-run-clang-tidy-itself this is normal :-/ And the alternative is to disable checks on headers or something. Not sure what to do from there though.

**Comment by jhasse** [comment]
hm ... it takes about 2.5 minutes on my laptop, something seems off. We should at least separate it into its own dedicated job so that it runs in parallel.

The best solution would be to add validation nodes support to ninja_syntax.py and then add validation nodes for clang-tidy to configure.py - so that it runs alongside the build with ninja itself.

**Comment by digit-google** [comment]
The last clang-tidy run took 59 minutes on one of my latest pushes! I don't think running this in parallel with validation actions will help much.

Besides, the output is too verbose and undecipherable; it already reports tons of warnings in the code that we do not care about (otherwise we would have fixed them a long time ago), and complains about really trivial stuff like the name of arguments in function signature and implementation being different.

At this point, I consider this more a nuisance than a feature and would suggest removing this step entirely from our Github CI workflows :-(

**Comment by jhasse** [comment]
Seems there really was something wrong with run-clang-tidy / Ubuntu / our setup. I've moved clang-tidy to the fedora task and it even isn't the longest running job.

I've also colored the output which makes it a lot more readable.

**Comment by digit-google** [comment]
Thanks a ton, that's even better!
