### ISSUE TITLE
Timestamps on windows

### ISSUE THREAD

**Issue by jlonnberg** [ninja-build/ninja#2465]
Hi,

I've encountered as very strange situation when running ninja on Windows.
I build a simple example, the build is successful and the .ninja_log file is generated with some timestamps for each included file. However, running "ninja -t restat" directly afterwards will update the timestamps for each file, i.e, increase the value. My expectation would be that the timestamps in the .ninja_log should be up-to-date after the build, and performing a restat just after a build should not change the content of the log file.

For us, this triggers strange rebuilds due to the small changes in the timestamps for some files.

Is this something that is known?

**Comment by digit-google** [comment]
This is by design. The timestamps in the build log are _not_ always filesystem timestamps.

When a command uses the `restat = 1` feature, the timestamp recorded in the build log corresponds to the time when the command was started, if it didn't modify its input.

This means that for some output, the build log timestamp will be newer (greater) than the one on the filesystem.

This is also what makes the feature work: it tells Ninja on the next invocation to ignore the filesystem timestamp, and thus avoid rebuilding the output if none of its inputs have changed since the last command was run.

When you call the `restat` tool, all timestamps in the log are updated directly from the filesystem values (and would thus generally _decrease_). This explains the update in values that you are seeing in the log.

This will trigger rebuilds of the command the next time Ninja is invoked, if any of its input is newer than the current output file timestamp.
