### ISSUE TITLE
Windows exe doesnt run 

### ISSUE THREAD

**Issue by adrianblazeusz** [ninja-build/ninja#2469]
I can't run windows exe by clicking ninja.exe

**Comment by digit-google** [comment]
There is not enough information here to understand what's wrong. Please specify:

1) What Ninja binary are you talking about exactly? And how did you get it / copy it to your machine ?

2) What do you expect clicking on the binary do? Ninja is a command-line tool that must be invoked from a build directory to do anything useful, otherwise, it will exit immediately with an error. Clicking on it is likely to not do anything anyway.

3) Can you invoke it from the command-line, if so, what is the error message you are seeing?
