### ISSUE TITLE
The need for CLICOLOR_FORCE=1 breaks good old -fdiagnostics-color=always

### ISSUE THREAD

**Issue by anordal** [ninja-build/ninja#2476]
How to enable colorful compiler output in CMake now that Ninja strips color codes?

`CLICOLOR_FORCE` is an environment variable. **That is a problem: I can't set it in CMake.**
Well, I can set environment variables in CMake, but that unsurprisingly has no effect when running `ninja` directly.

Context: The [recommendation](https://github.com/ninja-build/ninja/wiki/FAQ) has always been this, and this is what's no longer enough:

```cmake
if("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
    add_compile_options(-fdiagnostics-color=always)
else()
    add_compile_options(-fcolor-diagnostics)
endif()
```

As of Ninja 1.12.1, Ninja now strips the color codes anyway. :-(
Thus, it doesn't work by default, and it appears unfixable in CMake, so everyone needs to know about and deal with `export CLICOLOR_FORCE=1` to make it work.

I also tried [CMAKE_COLOR_DIAGNOSTICS](https://cmake.org/cmake/help/git-stage/variable/CMAKE_COLOR_DIAGNOSTICS.html), but I suspect it's broken for the same reason.
Is there anything I can set in CMake to restore the old behaviour?

**Comment by digit-google** [comment]
As far as I understand, you should set `CLICOLOR_FORCE=1` in your environment before calling `ninja`. E.g. `CLICOLOR_FORCE=1 ninja`.

IIRC, setting environment variables in CMake (or adding compiler options as in your example) only affects the commands launched by Ninja, but these will be ignored when invoking the Ninja program itself. There is nothing you can do in CMake itself to override that, as far as I know.

And `CLICOLOR_FORCE` is supported by many tools, including GCC and Clang, so using it should avoid the need for compiler options or `CMAKE_COLOR_DIAGNOSTICS`, which is better because it means you don't need to regenerate your build plan just to switch between colored vs non-colored outputs, in case you need that.

**Comment by jhasse** [comment]
Nothing was changed with regards to stripping of color codes and CLICOLOR_FORCE.

Something else must be going on.

If ninja isn't running in a tty it strips ansi escape codes, this was done even before CLICOLOR_FORCE was added.

**Comment by anordal** [comment]
Indeed, on closer inspection, it's not Ninja. The only use of CLICOLOR_FORCE here is if ninja itself isn't running in a terminal:

line_printer.cc
```C++
const char* term = getenv("TERM");
smart_terminal_ = isatty(1) && term && string_view(term) != "dumb";
supports_color_ = smart_terminal_;
if (!supports_color_) {
    const char* clicolor_force = getenv("CLICOLOR_FORCE");
    supports_color_ = clicolor_force && std::string_view(clicolor_force) != "0";
}
```

Yes, I have a feeling it must be something in my cmake files. I don't have a minimal reproducer yet, but it doesn't happen with a minimal example. It's not ccache either. Does anyone have a clue what else could be causing me to need CLICOLOR_FORCE=1?
