### ISSUE TITLE
Tons of include file notices when building with Chinese version of Visual Studio 2010

### ISSUE THREAD

**Issue by sfcheng** [ninja-build/ninja#613]
When building chromium with ninja with Chinese version of Visual Studio 2010, the console window outputs tons of include file notices and thus greatly slows down the building process. The notice is like:

注意： 包含文件：include file path

The English equivalent is：
Note: including file: .....

Perhaps ninja is stripping the include notices based on the English words only.

**Comment by fbridault** [comment]
With a french local, ninja 1.8.2 and CMake 3.10.2, this still happens...

**Comment by nico** [comment]
#665 added msvc_deps_prefix. Does cmake set that? @syntheticpp @mathstuf

**Comment by mathstuf** [comment]
@nico I see [code in CMake](https://gitlab.kitware.com/cmake/cmake/blob/d7204e649ed4ebb19bb341b4e49eb51514364922/Source/cmLocalNinjaGenerator.cxx#L80) which references it.

**Comment by dtaralla** [comment]
Still happening on Visual Studio Community 15.9.7...

**Comment by DrFrankenstein** [comment]
For the record, this is still happening to me with the following configuration:
CMake 3.14
Ninja 1.8.2 (the one that ships with Visual Studio 2019)
French locale.

And for those who also hit this issue, my workaround was to comment out the following line in `$CMAKE_PATH\share\cmake-3.14\Modules\Platform\Windows-MSVC.cmake`:
`#set(CMAKE_NINJA_DEPTYPE_${lang} msvc)` (line 368 in mine)

This unfortunately causes CMake to generate `deps = gcc` instead of juste removing the deps line, but that hasn't seemed to break my builds. YMMV.

**Comment by mathstuf** [comment]
Setting `deps = gcc` is probably benign without setting `depfile` as well.

**Comment by jonesmz** [comment]
@DrFrankenstein Would you be willing to try reproducing this after applying this PR to the ninja codebase? https://github.com/ninja-build/ninja/pull/1671

**Comment by DrFrankenstein** [comment]
I'll give it a shot this week!

**Comment by DrFrankenstein** [comment]
Unfortunately not. I built ninja from that branch, then used that version of ninja to build itself again, and it still leaked the include messages to the terminal.

**Comment by jonesmz** [comment]
It seems to me like the issue here might be with the MSVC include handler.

Is the grammar for that not recognizing the output from cl.exe correctly?

**Comment by jonesmz** [comment]
Well... 

It looks like it's a problem with hardcoded english.

https://github.com/ninja-build/ninja/blob/master/src/clparser.cc
```
string CLParser::FilterShowIncludes(const string& line,
                                    const string& deps_prefix) {
  const string kDepsPrefixEnglish = "Note: including file: ";
  const char* in = line.c_str();
  const char* end = in + line.size();
  const string& prefix = deps_prefix.empty() ? kDepsPrefixEnglish : deps_prefix;
  if (end - in > (int)prefix.size() &&
      memcmp(in, prefix.c_str(), (int)prefix.size()) == 0) {
    in += prefix.size();
    while (*in == ' ')
      ++in;
    return line.substr(in - line.c_str());
  }
  return "";
}
```

@DrFrankenstein

Do you feel like messing with that english prefix at the top of the function to see if it does you any better?

**Comment by DrFrankenstein** [comment]
Ha! I was actually going to look there tomorrow. Seems like you caught it before I had a chance to.

I just shut my computer down for the night. I'll get back to you tomorrow!

**Comment by DrFrankenstein** [comment]
It's worth noting, though, `deps_prefix` should contain the localized string as set in the build.ninja file. It only uses the hard-coded one if it's absent.

I suspect the logic just after it might be the actual culprit. But as I said, I'll do a proper investigation/debugging session tomorrow.

**Comment by DrFrankenstein** [comment]
The encodings don't match. `deps_prefix` is in Latin-1 (where the NBSP before the colons is 0xA0), and `line` is in CP437 for some reason (NBSP = 0xFF).
![image](https://user-images.githubusercontent.com/44741/74494239-6b4b8000-4ea2-11ea-9abb-831109c17e9e.png)

**Comment by DrFrankenstein** [comment]
Thinking back on this... this might be CMake's fault. On Windows, the `execute_process` command seems to convert the output of the command to UTF-8 internally (and accepts an optional `ENCODING` parameter to specify the output's encoding). It thus writes it back in UTF-8 in the rules.ninja file (where NBSP is 0xA0 and not 0xFF).

**Comment by mathstuf** [comment]
@bradking Thoughts on the encoding and prefix detection here?

**Comment by evmar** [comment]
Historically ninja has been encoding agnostic (as long as the encoding used the same byte as ASCII for '/').  However, Windows might make that difficult.

**Comment by bradking** [comment]
Ninja's `CLParser::FilterShowIncludes` is using `memcmp` to compare `msvc_deps_prefix` to lines in MSVC's output so indeed the value needs to be a bitwise match.  CMake may need some work to preserve that.  CMake currently converts to UTF-8 internally so perhaps all that is missing is converting back to the codepage's encoding when writing the value to `build.ninja`.

IIRC, MSVC's output encoding can be affected by environment variables and/or flags.  That means we may end up with the compiler output in a different encoding than the codepage in which Ninja is operating and using to interpret strings in `build.ninja`.  Such cases may require extra support from Ninja to handle but further investigation would be needed.

**Comment by DrFrankenstein** [comment]
I couldn't find any environment variable affecting the codepage used by CL. I think it just uses the codepage associated with the process (which is based on the system's regional settings, or by the console settings if the process is running in one).

However, there _is_ an environment variable that sets the language used by CL, `VSLANG`, which can be useful as a workaround for users affected by this bug. Setting `VSLANG=1033` before generating the ninja files will avoid the issue altogether.

**Comment by evmar** [comment]
Just to restate my above comment in different words: Ninja treats its input files as (encodingless) bytes, and does encoding-ignorant byte comparisons of strings, to attempt to evade these issues.  You need the bytes that appear in the build.ninja file to match the bytes that ninja reads from the process stdout, but ninja doesn't care about encodings.

**Comment by Krantz-XRF** [comment]
After CMake generating all the build files, I manually converted `rules.ninja` to UTF-8 which contains a line `msvc_deps_prefix = 注意: 包含文件:  `, and then things got fixed. I guess changes could be done to CMake so that it always converts `rules.ninja` to UTF-8?

I have no experience working on locales other than code page 936 or 65001, so I have no idea whether the solution above is a universal fix, though.

**Comment by YannKer** [comment]
Same problem and manage to erase this output with add /W2 instead of /W3 in CMAKE_CXX_FLAGS

**Comment by benmcmorran** [comment]
This is related to #1766

**Comment by Krysl** [comment]
as sgraham said:
> On an English install "Note: including file:%s%s\n" appears as resource in the string table in VC\bin\1033\clui.dll.

I write a script [find_msvc_prefix.py](https://gist.github.com/Krysl/3e9a633536c2562714bfc61296733b42) to check all clui.dll on my pc, it seems like all "Note: including file:%s%s\n" are at similar place `string table/26:1033`/`408`
![RH_clui dll_stringtable](https://user-images.githubusercontent.com/5905801/126688842-be17c052-5e12-4808-b5d1-6eb50972f1bf.png)
<img width="1125" alt="find_msvc_prefix" src="https://user-images.githubusercontent.com/5905801/126688844-6b2f280e-7318-491c-be59-abc65db09ca9.png">

## Plan A
- find if  `clui.dll` is in `1033` sub folder of `cl.exe`
    - if it exist, search the  "Note: including file:%s%s\n" in the dll, find out if it is in `string table/26:1033`/`408` 
        - find other `\d+` sub folder of `cl.exe`, get the string in the same plece (`string table/26:1033`/`408`)
    - if not exist, take the risk to use the same location above in `\d+` sub folder of `cl.exe`
- Maybe we can use a global config file to cache the results
    - when find new compiler, update it
- After got the strings, use a string[] to match in the `CLParser::FilterShowIncludes`
### problems
- There is no guarantee that Microsoft will use the same location and the same dll every time
- Code page problem.  
- Too complicated, VS2019 have only 14 language packs. a config file is enough. At most, just adjust the string order by detecting the locale of the PC

## Plan B
'global config' or 'environment variable'

## Plan C
Patch all the `clui.dll`, make all the "Note: including file:" in various languages to English version.  

advantage:
- If use this, there are no codepage problem on this, string in ANSI or UTF8 are same if it's in English version.
- do not need to change the ninja's source code.
- even if some codebase already add the `msvc_deps_prefix`, just make 2nd compare in `CLParser::FilterShowIncludes` can fix this.

Disadvantage:
- copyright problem?

**Comment by amasciotta** [comment]
Similar issue here: I've got Windows localized in italian, and VS2019 in english. Ninja outputs the italian "Nota: file incluso" string. Setting `VSLANG=1033` in the console before calling vcvars32/64 solved the issue.

**Comment by vincent-nv** [comment]
Hi, the other problem reported with #2039 is how to block theses messages ? They increase a lot the build time.

**Comment by evilenzo** [comment]
Similar issue on last Visual Studio Preview 2022 17.2. Tons of "Note including file: foo.h" even without /showincludes option set. So annoying

**Comment by cpsauer** [comment]
Hey all! Came across this while writing some Bazel tooling. After some experimenting, we ended up matching all the languages rather than using VSLANG=1033, because the latter doesn't work if the user doesn't have the English language pack installed. (Seems to work otherwise, though.)

**Comment by GuoZiyangTYUST** [comment]
A solution not very good:
use Clang rather than MSVC 

[build] [50/408   8% :: 2.247] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionDispatch/btSphereTriangleCollisionAlgorithm.obj
[build] [51/408   8% :: 2.265] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionDispatch/SphereTriangleDetector.obj
[build] [52/408   8% :: 2.280] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionDispatch/btSphereSphereCollisionAlgorithm.obj
[build] [53/408   8% :: 2.295] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btBox2dShape.obj
[build] [54/408   9% :: 2.311] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionDispatch/btCollisionWorldImporter.obj
[build] [55/408   9% :: 2.348] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btCapsuleShape.obj
[build] [56/408   9% :: 2.474] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConcaveShape.obj
[build] [57/408   9% :: 2.487] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionDispatch/btInternalEdgeUtility.obj
[build] [58/408  10% :: 2.511] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConeShape.obj
[build] [59/408  10% :: 2.600] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConvexInternalShape.obj
[build] [60/408  10% :: 2.819] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConvexPointCloudShape.obj
[build] [61/408  10% :: 2.841] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConvex2dShape.obj
[build] [62/408  11% :: 2.879] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btEmptyShape.obj
[build] [63/408  11% :: 2.927] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btCylinderShape.obj
[build] [64/408  11% :: 2.961] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConvexTriangleMeshShape.obj
[build] [65/408  11% :: 3.022] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btCollisionShape.obj
[build] [66/408  12% :: 3.083] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConvexShape.obj
[build] [67/408  12% :: 3.102] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btBvhTriangleMeshShape.obj
[build] [68/408  12% :: 3.125] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btMinkowskiSumShape.obj
[build] [69/408  12% :: 3.143] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btHeightfieldTerrainShape.obj
[build] [70/408  12% :: 3.222] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btMiniSDF.obj
[build] [71/408  13% :: 3.252] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btCompoundShape.obj
[build] [72/408  13% :: 3.304] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConvexHullShape.obj
[build] [73/408  13% :: 3.418] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btOptimizedBvh.obj
[build] [74/408  13% :: 3.497] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btPolyhedralConvexShape.obj
[build] [75/408  14% :: 3.544] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btConvexPolyhedron.obj
[build] [76/408  14% :: 3.578] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btSphereShape.obj
[build] [77/408  14% :: 3.631] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btSdfCollisionShape.obj
[build] [78/408  14% :: 3.676] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btTriangleCallback.obj
[build] [79/408  15% :: 3.753] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btTetrahedronShape.obj
[build] [80/408  15% :: 3.771] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btStaticPlaneShape.obj
[build] [81/408  15% :: 3.797] Building CXX object Engine/ThirdParty/bullet/bullet3/src/BulletCollision/CMakeFiles/BulletCollision.dir/CollisionShapes/btMultimaterialTriangleMeshShape.obj

**Comment by hez2010** [comment]
Hit this issue as well, so we just switched to msbuild from ninja and the issue was gone. Unexpectedly found that msbuild has been far faster than before :D

**Comment by kangjianbin** [comment]
I guess the bug is in cmake.

CMake can detect the prefix correctly, and stores it in its variable 'CMAKE_CL_SHOWINCLUDES_PREFIX' (or CMAKE_CXX_CL_SHOWINCLUDES_PREFIX). Note that this prefix is not utf-8 encoding. For example, in my locale it is encoded in 'GB18030'.
However, when creating rules.ninja, cmake converts this prefix to utf-8 and saves the converted data to msvc_deps_prefix.

During build, msvc_deps_prefix (utf-8 encoding) cannot match MSVC's output (gb18030 enconding, et al), so Ninja reports lots of include files.

I switched to cmake-3.20, which doesn't convert the prefix to utf-8, and everything works well.

**Comment by mathstuf** [comment]
> I switched to cmake-3.20, which doesn't convert the prefix to utf-8, and everything works well.

So this can be closed then?

**Comment by bradking** [comment]
A relevant change in CMake is [MR 5089](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5089), first included in CMake 3.19.  It switched to writing the `msvc_deps_prefix` as a raw byte sequence regardless of the encoding of `build.ninja`, since Ninja only compares raw byte sequences to look for such lines in the compiler output.

The best path forward for Ninja upstream is #1812/#2200, which add support for using `cl`'s new equivalent to a gcc depfile.

**Comment by kangjianbin** [comment]
> > I switched to cmake-3.20, which doesn't convert the prefix to utf-8, and everything works well.
> 
> So this can be closed then?

No as it still exists in CMake 3.24. I checked [MR 5089](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5089), looks like the issue was introduced again in [MR 5860](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5860) . When Ninja version is larger than 1.11, CMake assumes Ninja supports UTF-8; so it writes rules.ninja with UTF-8.

**Comment by bradking** [comment]
@kangjianbin thanks.  Please open a CMake upstream issue for that.  Include details about the actual encoding of the byte sequence that you're observing.

**Comment by kangjianbin** [comment]
Created issue https://gitlab.kitware.com/cmake/cmake/-/issues/24068

**Comment by kangjianbin** [comment]
CMake 3.25 works for me. Thanks.

**Comment by fcharlie** [comment]
When I update cmake to 3.25 this issue doesn't seem to be resolved.

```
cmake: 3.25.0
ninja: 1.11.1
chcp: 936
```

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6904176/202849458-9623232e-3a93-441b-b2a2-74a919d51aa3.png">

Whether you run `cmake --build .` Or `ninja all`, the result is the same. Also, modifying the code page to 54936 has no effect.

**Comment by kangjianbin** [comment]
> Enable `Beta: Use Unicode UTF-8 for worldwide language support` and restart Windows:

Did cmake detect the prefix correctly?

**Comment by waruqi** [comment]
We can run `cl.exe --showIncludes` to try compiling a empty file, then detect the note include prefix automatically.

see https://github.com/xmake-io/xmake/blob/ec1bedd448b5e50aab8cd83792fb7e855b1fa680/xmake/modules/private/tools/cl/parse_include.lua#L30

https://github.com/xmake-io/xmake/blob/ec1bedd448b5e50aab8cd83792fb7e855b1fa680/xmake/plugins/project/ninja/build_ninja.lua#L179

and we need also change build.ninja encoding (utf8) to `GBK` or ....

BTW, if `/sourceDependencies` can be supported, it will be better. waiting for https://github.com/ninja-build/ninja/issues/1806

**Comment by cpsauer** [comment]
If useful: I *think* that the last time I checked out /sourceDependencies (and friends)  they were only for module dependencies, rather than the normal header inclusion you'd need for this.

Creating a test to extract the include note is very clever :)

**Comment by mathstuf** [comment]
> I think that the last time I checked out /sourceDependencies (and friends) they were only for module dependencies, rather than the normal header inclusion you'd need for this.

Early revisions of the P1689 format included this information but it was excluded in order to keep the initial revisions focused and less cluttered.

**Comment by dengchcs** [comment]
I'm using Visual Studio 2019 with Chinese locale, and solved this issue simply by upgrading my cmake version to 3.26. 

将 cmake 版本升级到 3.26 即可

**Comment by eli-schwartz** [comment]
> We can run `cl.exe /nologo /showIncludes /c /Foxx xxx.c` to try compiling a empty file, then detect the note include prefix automatically.

Certainly, meson does this as well: https://github.com/mesonbuild/meson/blob/ef5da765af7c5687228ed6e77a19d20bc474c4a4/mesonbuild/backend/ninjabackend.py#L526-L573

So does cmake: https://gitlab.kitware.com/cmake/cmake/-/blob/1ec4c6579117634ddb20962cdb63313dbf79887e/Modules/CMakeDetermineCompilerId.cmake#L1131

Both use regexes a lot more complicated than yours, by the way -- I don't know whether that's necessary but it's plausible that you will sometimes fail to find the right info.

**Comment by eli-schwartz** [comment]
> IMO it's ninja to offer an option to hide it.

Ninja does since about five years ago, it's not clear why the ticket is still open.

> As a sidenote, if I use a different generator than ninja with the same compiler and same Cmake I don't have all of these prints.

Probably the Make backend doesn't support showIncludes at all, so you don't get reliable builds. Meanwhile, Visual Studio "cheats" since it's responsible for emitting the translated messages and can always tell exactly what part it is.

Unfortunately everyone other than Microsoft needs to work around Microsoft's non-interoperable design of translating machine-readable messages into the user's prose language.

**Comment by waruqi** [comment]
> > We can run `cl.exe /nologo /showIncludes /c /Foxx xxx.c` to try compiling a empty file, then detect the note include prefix automatically.
> 
> Certainly, meson does this as well: https://github.com/mesonbuild/meson/blob/ef5da765af7c5687228ed6e77a19d20bc474c4a4/mesonbuild/backend/ninjabackend.py#L526-L573
> 
> So does cmake: https://gitlab.kitware.com/cmake/cmake/-/blob/1ec4c6579117634ddb20962cdb63313dbf79887e/Modules/CMakeDetermineCompilerId.cmake#L1131
> 
> Both use regexes a lot more complicated than yours, by the way -- I don't know whether that's necessary but it's plausible that you will sometimes fail to find the right info.

I see that cmake detects it automatically, but I use cmake 3.24.2 and it still doesn't work. Is there any special configuration I need to do to turn it on?

**Comment by JKwarn** [comment]
> I'm using Visual Studio 2019 with Chinese locale, and solved this issue simply by upgrading my cmake version to 3.26.
> 
> 将 cmake 版本升级到 3.26 即可


CMake 3.26 works for me. 
升级到3.26对我来说是有用的。


OS: Windows 11 22H2
QT Creator: 10.0.1

**Comment by jhasse** [comment]
Seems to be fixed. Please reopen if it still applies.

**Comment by Ri0n** [comment]
QtCreator comes with CMake 3.27.7 and it's reproducible there.

**Comment by mathstuf** [comment]
Can you please report back to CMake's issue tracker there with more details?

**Comment by s9w** [comment]
This is still happening btw, not fixed at all

**Comment by jhasse** [comment]
Please include even less information so we have ABSOLUTELY no way of reproducing. If you really want to include a version number of some tool, always make sure you omit either CMake's version or Ninja's. Thanks!

**Comment by s9w** [comment]
You're welcome. And good luck with that attitude.

**Comment by MagentaTreehouse** [comment]
Here's a repro:

ninja version 1.12.1
cmake version 4.0.1
MSVC version 19.43

PowerShell default code page: 936

Configure in default code page, then switch to code page 65001 and build. `Note: including file` messages will be printed.

[repro.zip](https://github.com/user-attachments/files/19925028/repro.zip)

<details>

<summary>Repro content preview</summary>

Tree:
```
D:\dev\projects\repro
│   CMakeLists.txt
├───include
│   └───foo
│           bar.hpp
└───src
        bar.cpp
```

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.29)

project(foo LANGUAGES CXX)

add_library(libfoo)
target_sources(libfoo
  PRIVATE src/bar.cpp
  PUBLIC FILE_SET headers TYPE HEADERS BASE_DIRS include FILES
    include/foo/bar.hpp
)
```

bar.hpp:
```c++
#ifndef FOO_BAR_HPP
#define FOO_BAR_HPP
void bar();
#endif
```

bar.cpp:
```c++
#include <foo/bar.hpp>
void bar() {}
```

</details>

<details>

<summary>Commands and output</summary>

```console
PS D:\dev\projects\repro> cmake -Bbuild -GNinja
-- The CXX compiler identification is MSVC 19.43.34810.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.43.34808/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features       
-- Detecting CXX compile features - done
-- Configuring done (1.5s)
-- Generating done (0.0s)
-- Build files have been written to: D:/dev/projects/repro/build
PS D:\dev\projects\repro> cd .\build\
PS D:\dev\projects\repro\build> chcp 65001
Active code page: 65001
PS D:\dev\projects\repro\build> ninja libfoo
[1/2] Building CXX object CMakeFiles\libfoo.dir\src\bar.cpp.obj
Note: including file: D:\dev\projects\repro\include\foo/bar.hpp
[2/2] Linking CXX static library libfoo.lib
```

</details>

**Comment by eli-schwartz** [comment]
> Configure in default code page, then switch to code page 65001 and build. `Note: including file` messages will be printed.

If you have to change the codepage to trigger the issue, this suggests that ninja is now looking for the wrong thing, and you need to regenerate your ninja file in order to have it specify the correct search string?

**Comment by jhasse** [comment]
Thanks @MagentaTreehouse for the reproducer :)

Yes, I think changing the codepage after configure is something that can mess up the detection. It is rather brittle and a solution like #2200 should be the way forward instead.

**Comment by mathstuf** [comment]
Changing the environment after configuring and before the build sounds…unsupportable in general. Why not use a consistent environment?

**Comment by MagentaTreehouse** [comment]
My local development uses the CMake Tools extension as the configuration provider. With this extension (or with an IDE), the configure command is invoked in the default code page. But I would like MSVC to run in code page 65001, otherwise one of my tools may have trouble handling MSVC output. (I prefer not to change my default code page because that would mess up output for some other programs.)

**Comment by MagentaTreehouse** [comment]
Looks like issue #1766 is related?

**Comment by mathstuf** [comment]
65001 is UTF-8 (so, therefore is the sane thing). Can you somehow have the IDE (or at least CMake) also in that codepage as CMake also heavily prefers working with UTF-8?

**Comment by bradking** [comment]
For reference, CMake detects the compiler's `/showIncludes` prefix in code [here](https://gitlab.kitware.com/cmake/cmake/-/blob/v4.0.1/Modules/CMakeDetermineCompilerId.cmake#L1256-1282) as part of the initial environment/toolchain inspection.  Then code [here](https://gitlab.kitware.com/cmake/cmake/-/blob/v4.0.1/Source/cmLocalNinjaGenerator.cxx#L104) in the `Ninja` generator writes the `msvc_deps_prefix = ...` binding to the generated `ninja` build manifest.  `cl` changes its `/showIncludes` prefix based on the console's output code page, so one must use a consistent code page between configuring and building.
