### ISSUE TITLE
More user-friendly reports for "multiple rules generate targetname"

### ISSUE THREAD

**Issue by ramosian-glider** [ninja-build/ninja#718]
I'm debugging a dependency loop in Chromium ninja files (http://crbug.com/346703) which is reported as follows:

ninja: Entering directory `out_cxx/Release/'
ninja: warning: multiple rules generate chrome. builds involving this target will not be correct; continuing anyway
ninja: error: dependency cycle: chrome -> obj/chrome/chrome.actions_depends.stamp -> chrome

As a ninja n00b I consider this report quite puzzling. I think it could help if ninja printed the locations of the duplicate rules, i.e.:
ninja: warning: multiple rules generate chrome:
  out_cxx/Release/build.ninja:chrome
  obj/chrome/chrome_initial.ninja:chrome
builds involving this target will not be correct; continuing anyway.

**Comment by stek29** [comment]
<sub>I hate asking this but</sub>
Any progress on this?

**Comment by nico** [comment]
No. Would the output in https://github.com/ninja-build/ninja/issues/821#issuecomment-56199901 have helped you?

**Comment by nico** [comment]
Actually, there has been progress now that I think of it. The error is now emitted by the manifest parser, and if you pass `-w dupbuild=err` you'll get

- an error instead of a warning
- a line number where the error appears

And on trunk, `-w dupbuild=err` is now the default. So I think this is basically done.
