### ISSUE TITLE
request: new environment variable NINJA_OPTIONS (or NINJA_FLAGS)

### ISSUE THREAD

**Issue by urkle** [ninja-build/ninja#797]
This would allow global user-override parameters such as specifying -j#  

e.g.

export NINJA_OPTIONS=-j6

would force all builds to be run with -j6 instead of the default. (unless overridden on the commandline of a particular execution of ninja).

**Comment by itensionanders** [comment]
Why not just use $NINJAFLAGS ? Then it could fit *both* of `-j` and `-l`, just like with $MAKEFLAGS.

**Comment by evmar** [comment]
See #1370 about adding environment variables.

**Comment by martong** [comment]
Just ran into this and saw that the pull request for `NINJA_FLAGS` was not accepted. For those who still seek a solution ... this idea helped in my case (together with zsh): `alias ninja="ninja -j48 "`

**Comment by eli-schwartz** [comment]
The independent Ninja build language reimplementation https://github.com/michaelforney/samurai supports this via the environment variable SAMUFLAGS. Simply use samu anywhere you'd otherwise use ninja, or install samu as your system /usr/bin/ninja (some linux distros have options to install this competing implementation as the default, or only, ninja).

**Comment by latentPrion** [comment]
> Just ran into this and saw that the pull request for `NINJA_FLAGS` was not accepted. For those who still seek a solution ... this idea helped in my case (together with zsh): `alias ninja="ninja -j48 "`

Hey, this specific solution didn't work for me but I got an idea based on it that did work: instead of using a bash alias, I just wrapped my `/usr/bin/ninja` and `/usr/bin/make` binaries in a shell script that filters out prior-supplie `-j` options and replaces it with my desired `-j` option value. Basically, I intercept calls to `ninja`/`make` and ensure that their `-j` option values conform to my preferences.

The following scripts worked for me, and helped me to build the wheel for the python `xformers` package. Without this, the Nvidia CUDA compiler was using 3-16GiB of RAM to compile each cuda kernel source file, and parallel compilation would just result in the Linux kernel OOM-killing the build.

```
#!/bin/bash
# Wrapper for ninja that limits jobs to 2
# Usage: ninja-wrapper.sh [args...]

WRAPPER_SCRIPT="$(dirname "$0")/job-limited-wrapper.sh"
REAL_NINJA="$(which -a ninja | grep -v "$(readlink -f "$0")" | head -1)"

if [ -z "$REAL_NINJA" ]; then
    REAL_NINJA="/usr/bin/ninja"
fi
REAL_NINJA="/usr/bin/ninjareal"

exec "$WRAPPER_SCRIPT" "$REAL_NINJA" "$@"
```

```
#!/bin/bash
# Enhanced wrapper script that filters out all -j flags and ensures only -j 2 is used
# Usage: job-limited-wrapper.sh <real-binary> [args...]

if [ $# -lt 1 ]; then
    echo "Usage: $0 <real-binary> [args...]" >&2
    exit 1
fi

REAL_BINARY="$1"
shift

# Filter out all -j flags and their values
FILTERED_ARGS=()
SKIP_NEXT=false

for arg in "$@"; do
    if [ "$SKIP_NEXT" = true ]; then
        SKIP_NEXT=false
        continue
    fi
    
    # Check if this is a -j flag (with or without value)
    case "$arg" in
        -j)
            # -j followed by a number in next arg, skip both
            SKIP_NEXT=true
            continue
            ;;
        -j*)
            # -jN format, skip it
            continue
            ;;
        --jobs=*)
            # --jobs=N format, skip it
            continue
            ;;
        --jobs)
            # --jobs followed by a number in next arg, skip both
            SKIP_NEXT=true
            continue
            ;;
        *)
            # Regular argument, keep it
            FILTERED_ARGS+=("$arg")
            ;;
    esac
done

# Add -j 2 to the filtered arguments
FILTERED_ARGS+=("-j" "1")

# Execute the real binary with filtered arguments
exec "$REAL_BINARY" "${FILTERED_ARGS[@]}"
```
