### ISSUE TITLE
ninja: error: remove(someDirectory) Permission denied. Windows

### ISSUE THREAD

**Issue by agalapovs** [ninja-build/ninja#828]
After running "ninja -t clean" got "Permission denied" while deleting a folder.

MSDN describe stdio.h remove() as function for deleting files (not directories), on the other hand Linux man pages describe it as function for deleting files and folders. Could be a platform specific problem.

Calling _rmdir() (http://msdn.microsoft.com/en-us/library/wt8es881.aspx) do the trick.

**Comment by crispyzeal** [comment]
+1

**Comment by dkreuter** [comment]
On linux directories are only removed when they're empty. Can the behaviour be changed to recursive removal? Or maybe give the buildscript an opportunity to do clean up before -t clean tries to remove() the directory?

**Comment by mbodmer** [comment]
Same issue here.
Directory was generated by rule created from CMake add_custom_command()

ninja clean 
[1/1] Cleaning all built files...
FAILED: /usr/bin/ninja -t clean
ninja: error: remove(mydirectory): Directory not empty

**Comment by KUGA2** [comment]
Issue is still present in 3.7.2 on Windows.

**Comment by jhasse** [comment]
> On linux directories are only removed when they're empty. Can the behaviour be changed to recursive removal?

Would be a pretty big change and people might lose their files. See #1334 btw.

Let's keep this issue about the Windows-only "Permission denied" error though.

**Comment by jralls** [comment]
Microsoft's documentation for [`remove`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/remove-wremove?view=vs-2019) says that it "sets errno either to EACCES to indicate that the path specifies a read-only file, **specifies a directory,** or the file is open...", so that explains what's going on. It doesn't matter if the directory is empty, one simply can't call `remove` on a directory if using msvcrt.
